/*
 * To change this license header, choose License Headers in Project Properties.
 * To ch    @Override
    public void textValueChanged(TextEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
ange this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shu;
import javax.swing.*;
import java.sql.*;
import java.sql.Date;
import java.text.SimpleDateFormat;
//import java.util.Date;

/**
 *
 * @author Shubham
 */
public class addemployee extends javax.swing.JFrame {

    /**
     * Creates new form addemployee
     */
    public addemployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t4 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t7 = new com.toedter.calendar.JDateChooser();
        submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("EmpId");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(206, 60, 78, 32);

        t1.setText(" ");
        jPanel1.add(t1);
        t1.setBounds(477, 48, 170, 38);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(206, 113, 49, 41);

        t2.setText(" ");
        jPanel1.add(t2);
        t2.setBounds(477, 114, 170, 41);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 153));
        jLabel3.setText("Email");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(206, 173, 64, 47);

        t3.setText(" ");
        jPanel1.add(t3);
        t3.setBounds(477, 174, 170, 47);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 153));
        jLabel4.setText("Address");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(206, 259, 64, 29);

        t4.setColumns(20);
        t4.setRows(5);
        jScrollPane1.setViewportView(t4);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(477, 239, 170, 57);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 204));
        jLabel5.setText("city");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(206, 332, 48, 17);

        t5.setText(" ");
        jPanel1.add(t5);
        t5.setBounds(477, 319, 170, 42);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 204));
        jLabel6.setText("mobile_no");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(206, 389, 90, 23);

        t6.setText(" ");
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        jPanel1.add(t6);
        t6.setBounds(477, 379, 170, 34);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("Date");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(207, 458, 80, 17);

        t7.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(t7);
        t7.setBounds(477, 436, 170, 37);

        submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(153, 0, 153));
        submit.setText("submit");
        submit.setBorder(null);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(214, 502, 190, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 153));
        jButton1.setText("cancel");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 500, 180, 50);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("   Add Employee");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(290, 10, 210, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shu/i/back20button.png"))); // NOI18N
        jButton2.setText(" ");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 10, 42, 49);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        t4.setLineWrap(true);
        t4.setWrapStyleWord(true);
        try{
            if((((( (t2.getText().toString()!=null)&&(t3.getText().toString()!=null) )&&(t4.getText()!=null))&&(t5.getText().toString()!=null))&&(t6.getText().toString()!=null)))
            {
        Class.forName("com.mysql.jdbc.Driver");
        Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
        PreparedStatement ps=co.prepareStatement("insert into emp values(?,?,?,?,?,?,?)");
        int a=Integer.parseInt(t1.getText());
        ps.setInt(1, a);
        ps.setString(2,t2.getText());
        ps.setString(3,t3.getText());
        ps.setString(4,t4.getText());
        ps.setString(5,t5.getText());
        ps.setString(6,t6.getText());
     SimpleDateFormat sdf=new simpleDateFormat("yyyy-mm-dd");
        
        String date;
            date = sdf.format(t7.getDate());
      JOptionPane.showMessageDialog(null,date);
            
            
       
        ps.setString(7,date);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Add employee  succesfully");
         }
            else
            {
                
            JOptionPane.showMessageDialog(null,"all filed requried");
            
            }
        }catch(Exception e){
            
        JOptionPane.showMessageDialog(null,"all field requried");
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        t2.setText("");t3.setText("");t4.setText("");t5.setText("");t6.setText("");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
        String s=t6.getText();
        if(((s.length()>=10))&&(s.length()<11))
        {
            
          
        } else {
            JOptionPane.showMessageDialog(null,"invalid  number");
        }
    }//GEN-LAST:event_t6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
              try
        {
         
        Class.forName("com.mysql.jdbc.Driver");
        Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
        Statement ps=co.createStatement();
         
        ResultSet rs=ps.executeQuery(" select * from  emp ORDER BY emp_id DESC LIMIT 1;"); 
        
        while(rs.next())
        {
          //  model.addRow(new Ob  
            
             int a=rs.getInt(1);
             
              
                if(a< -1)
                {
                    
                    t1.setText("1");
                }
                else
                {   
             
             int c=a+1;
             t1.setText(""+c);
                }
        } 
   
        }catch(Exception e){JOptionPane.showMessageDialog(null,e);}
   
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        this.dispose();
        new employeesection().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
                UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
                //</editor-fold>
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton submit;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextArea t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private com.toedter.calendar.JDateChooser t7;
    // End of variables declaration//GEN-END:variables
}
