/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shu;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Shubham
 */
public class itemnameEntry extends javax.swing.JFrame {

    /**
     * Creates new form itemnameEntry
     */
    public itemnameEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        p1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText(" Item Name");

        t5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        t5.setText(" ");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Shopkepper name");
        p1.add(jLabel2);
        jLabel2.setBounds(310, 140, 160, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 153));
        jButton1.setText("add item");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        p1.add(jButton1);
        jButton1.setBounds(340, 356, 190, 44);

        cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(153, 0, 153));
        cancel.setText("cancel");
        cancel.setBorder(null);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        p1.add(cancel);
        cancel.setBounds(570, 356, 200, 47);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Item  name entry");
        p1.add(jLabel3);
        jLabel3.setBounds(425, 17, 200, 44);

        /*try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            Statement ps=co.createStatement();
            ResultSet rs=ps.executeQuery("select name from brand ");

            while(rs.next())
            {
                t2.setModel(new javax.swing.DefaultComboBoxModel<>(t2.addItem(rs.getString(2)));
                }
                // JOptionPane.showMessageDialog(null,"insert succesfully");

            }
            catch(Exception e){

                // JOptionPane.showMessageDialog(null,e);
            }*/
            t2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    t2MouseClicked(evt);
                }
            });
            t2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    t2ActionPerformed(evt);
                }
            });
            p1.add(t2);
            t2.setBounds(560, 130, 270, 40);

            jButton2.setText("jButton2");
            p1.add(jButton2);
            jButton2.setBounds(60, 520, 73, 23);

            jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shu/i/back20button.png"))); // NOI18N
            jButton3.setText(" ");
            jButton3.setBorder(null);
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });
            p1.add(jButton3);
            jButton3.setBounds(10, 10, 42, 49);

            jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel6.setText("Item_id");
            p1.add(jLabel6);
            jLabel6.setBounds(310, 70, 116, 43);

            t1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            p1.add(t1);
            t1.setBounds(560, 80, 270, 46);

            jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel7.setText("Item Name");
            p1.add(jLabel7);
            jLabel7.setBounds(310, 200, 116, 43);

            t3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            p1.add(t3);
            t3.setBounds(560, 190, 270, 46);

            jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel8.setText("Price");
            p1.add(jLabel8);
            jLabel8.setBounds(310, 260, 116, 43);

            t4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            p1.add(t4);
            t4.setBounds(560, 250, 270, 46);

            getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1010, 520));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            PreparedStatement ps=co.prepareStatement("insert into item values(?,?,?,?)");
            Statement s=co.createStatement();
            ResultSet sc=s.executeQuery("select * from item");
            while(sc.next())
            {
                    String sp=sc.getString(2);
                    if(sp.equals(t3.getText()))
                    {
                        JOptionPane.showMessageDialog(null,"Already record is insert");
                    }
                    else
                    {
                         ps.setString(1, (String) t2.getSelectedItem());
                         ps.setString(2,t3.getText());
                         ps.setInt(3,Integer.parseInt(t4.getText()));
                         ps.setInt(4,Integer.parseInt(t1.getText()));
                         ps.executeUpdate(); 
                         JOptionPane.showMessageDialog(null,"insert succesfully");
                    }
                    
            }
           // ps.setString(1,t4.getSelectdItem());
              
           // javax.swing.JOptionPane.showMessageDialog(null,"insert succesfully");

        }
        catch(Exception e){
JOptionPane.showMessageDialog(null,e);
           
           // javax.swing.JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
      t1.setText("");
      t3.setText("");
      t4.setText("");
      
        
    }//GEN-LAST:event_cancelActionPerformed

    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
        // TODO add your handling code here:
           // TODO add your handling code here:
    try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            Statement ps=co.createStatement();
            ResultSet rs=ps.executeQuery("select * from brand ");
           
            while(rs.next())
            {
                 
                String s=rs.getString(2);
                t2.addItem(s);
            } 
          }
            catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e);
            }
         
    }//GEN-LAST:event_t2MouseClicked

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            Statement ps=co.createStatement();
            ResultSet rs=ps.executeQuery("select * from brand ");
           
            while(rs.next())
            {
                 
                String s=rs.getString(2);
                t2.addItem(s);
            }
            
          }
            catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e);
            }
                  try
        {
         
        Class.forName("com.mysql.jdbc.Driver");
        Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
        Statement ps=co.createStatement();
         
        ResultSet rs=ps.executeQuery(" select * from  item ORDER BY item_id DESC LIMIT 1;"); 
        
        while(rs.next())
        {
            t1.setText(""+rs.getInt(4));
        }
        
        }catch(Exception e){}
       

    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new stocksection().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
         try {
                UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
                //</editor-fold>
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new itemnameEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel p1;
    private javax.swing.JTextField t1;
    private javax.swing.JComboBox<String> t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
