/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shu;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Shubham
 */
public class removeemployee extends javax.swing.JFrame {
DefaultTableModel model;
Object row[]=new Object[7];
    /**
     * Creates new form removeemployee
     */
    public removeemployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        p2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p2.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        this.setSize(500,500);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("emp_id");
        p2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 68, 63, 41));

        t1.setText(" ");
        p2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 69, 133, 41));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText(" Name");
        p2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 67, 73, 42));

        t2.setText(" ");
        p2.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 69, 121, 41));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("search");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        p2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 160, 124, 41));

        p3.setBackground(new java.awt.Color(153, 255, 102));
        p3.setLayout(null);
        p2.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 52, 149, 0));

        model=new DefaultTableModel();
        Object []data={ "emp_id", "Name", "mail", "address", "city", "Mobile_no", "Date"};
        model.setColumnIdentifiers(data);
        t3.setModel(model);

        /*
    );
    */
    jScrollPane1.setViewportView(t3);

    p2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 726, 220));

    jButton2.setText("remove");
    jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    p2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 160, 90, 43));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setText("                      Remove Employee");
    p2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 14, 237, 31));

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shu/i/back20button.png"))); // NOI18N
    jButton3.setText(" ");
    jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    p2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 42, -1));

    getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 520));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here

        int a=Integer.parseInt(t1.getText());
        String s=t2.getText();
        try
        {

            Class.forName("com.mysql.jdbc.Driver");
            Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            Statement ps=co.createStatement();
            ResultSet rs=ps.executeQuery("select * from emp  where  emp_id="+a);

            while(rs.next())
            {
                //  model.addRow(new Object[]{ rs.getInt(1),rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
                row[0]=rs.getInt(1);
                row[1]=rs.getString(2);
                row[2]=rs.getString(3);
                row[3]=rs.getString(4);
                row[4]=rs.getString(5);
                row[5]=rs.getString(6);
                row[6]=rs.getString(7);
                model.addRow(row);
            }

        }catch(Exception e){JOptionPane.showMessageDialog(null,e);}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: 
        
            
          int a=Integer.parseInt(t1.getText());
          String s=t2.getText();
           int c=t3.getSelectedRow();
        
          model.removeRow(c);
        
            
        try
        {
         
        Class.forName("com.mysql.jdbc.Driver");
        Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
        PreparedStatement ps=co.prepareStatement("delete from emp where emp_id="+a);
        
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"delete succesfully");
        co.close();
         
     }catch(Exception e){}
        
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new employeesection().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { try {
                UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
                //</editor-fold>
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new removeemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTable t3;
    // End of variables declaration//GEN-END:variables
}
