/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shu;

import java.awt.Color;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.*;
import java.sql.Date.*;
import java.util.Locale;
/**
 *
 * @author Shubham
 */
public class stockentery extends javax.swing.JFrame {

    /**
     * Creates new form stockentery
     */
    public stockentery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t6 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        t3 = new javax.swing.JComboBox<>();
        j13 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        price = new javax.swing.JButton();
        t7 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Stock Entry");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shu/i/back20button.png"))); // NOI18N
        jButton1.setText(" ");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 920, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("stock_id");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 120, 30));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 230, 30));

        t4.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                t4InputMethodTextChanged(evt);
            }
        });
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel2.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 230, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Rate");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 90, 32));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Entry Date");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 90, -1));

        t6.setDateFormatString("yyyy-MM-dd\n");
        jPanel2.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 230, 35));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("item Name ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 90, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("total Quantity");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 100, 39));

        j2.setText(" ");
        jPanel2.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 100, 25));

        /*
        t3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        */
        t3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                t3ItemStateChanged(evt);
            }
        });
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel2.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 230, 30));

        j13.setText(" ");
        jPanel2.add(j13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 60, 50));

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        jPanel2.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 230, 40));

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(153, 0, 153));
        save.setText("add stock");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 180, 40));

        cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(102, 0, 204));
        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 230, 40));

        price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        price.setText("Price");
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel2.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, 28));
        jPanel2.add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 180, 30));

        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        jPanel2.add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 230, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Shop Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, 24));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         try
        {
         
        Class.forName("com.mysql.jdbc.Driver");
        Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
        Statement ps=co.createStatement();
         
        ResultSet rs=ps.executeQuery(" select * from  stockentry ORDER BY stock_id DESC LIMIT 1;"); 
        
        while(rs.next())
        {
          //  model.addRow(new Ob  
            
             int a=rs.getInt(7);
             if(a==0)
             {
                 t8.setText("1");
             }
             int c=a+1;
             t8.setText(""+c);
        } 
   
        }catch(Exception e){JOptionPane.showMessageDialog(null,"");}
                    
                              
        try
        {
         
        Class.forName("com.mysql.jdbc.Driver");
        Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
        Statement ps=co.createStatement();
         
        ResultSet rs=ps.executeQuery("select * from item"); 
        
        while(rs.next())
        {
          //  model.addRow(new Ob 
            t3.addItem(rs.getString(2));
             
        } 
   
        }catch(Exception e){JOptionPane.showMessageDialog(null,"");}
            try
        {
         
        Class.forName("com.mysql.jdbc.Driver");
        Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
        Statement ps=co.createStatement();
         
        ResultSet rs=ps.executeQuery("select * from item where item='"+t3.getSelectedItem()+"'"); 
        
        while(rs.next())
        {
          //  model.addRow(new Ob 
           t5.setText(""+ rs.getInt(3));
             
        } 
   
        }catch(Exception e){JOptionPane.showMessageDialog(null,"");}
                         

    }//GEN-LAST:event_formWindowOpened

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
        int l=Integer.parseInt(t4.getText());
        int m= Integer.parseInt(t5.getText());
        int n=l*m;
        t7.setText(""+n);
 int a=Integer.parseInt(t4.getText());
        j13.setVisible(false);
        
        try {
            Class.forName("com.mysql.jdbc.Driver");

            Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            Statement ps=co.createStatement();
            PreparedStatement os;
            ResultSet rs=ps.executeQuery("select * from avalible where item='"+t3.getSelectedItem().toString()+"'");
              
        while(rs.next())
        {
            
            
         
            
            
          int b=rs.getInt(2);
          int c=a+b;
          j13.setText(""+c);   
         
            
             os=co.prepareStatement("update avalible  set Qty='"+c+"' where item='"+t3.getSelectedItem()+"' ");
                 os.executeUpdate();
           JOptionPane.showMessageDialog(new Frame(),t3.getSelectedItem()+j13.getText(),"Stock",JOptionPane.DEFAULT_OPTION);
       
        } 
   
        }catch(Exception e){JOptionPane.showMessageDialog(null,e);}
                               
       
        
    }//GEN-LAST:event_priceActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
            try{
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
                PreparedStatement ps=co.prepareStatement("insert into stockentry values(?,?,?,?,?,?,?)");
                 
                PreparedStatement p;
                
                try{
                p=co.prepareStatement("insert into avalible values(?,?)");

                String s=t5.getText();
                p.setString(1,t3.getSelectedItem().toString());
                p.setInt(2,Integer.parseInt(t4.getText()));
                p.executeUpdate();
                }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);}
                ps.setString(1, t1.getText()); 
                ps.setString(2,t3.getSelectedItem().toString());
                ps.setString(3,t4.getText());
                ps.setString(4,t7.getText()); 
                try{
                //JOptionPane.showMessageDialog(null,t10.getDate());
                       try{
                ps.setString(5,((JTextField)t6.getDateEditor().getUiComponent()).getText());
                       }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);}
                ps.setString(6,t5.getText());
                try{
                ps.setInt(7,Integer.parseInt(t8.getText())); 
                }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);}
                 
                ps.executeUpdate();
}catch(Exception e){
                JOptionPane.showMessageDialog(null,e);}
                JOptionPane.showMessageDialog(null,"inssert succesfully");

            }
            catch(Exception e){

                JOptionPane.showMessageDialog(null,"helllo");
            }
        }
        catch(NullPointerException e){

            JOptionPane.showMessageDialog(null,"");
        }

    }//GEN-LAST:event_saveActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_t1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new stocksection().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_t5ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void t3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_t3ItemStateChanged
        // TODO add your handling code here:
                    try
        {
         
        Class.forName("com.mysql.jdbc.Driver");
        Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
        Statement ps=co.createStatement();
         
        ResultSet rs=ps.executeQuery("select * from item where item='"+t3.getSelectedItem()+"'"); 
        
        while(rs.next())
        {
          //  model.addRow(new Ob 
           t5.setText(""+ rs.getInt(3));
             
        } 
   
        }catch(Exception e){JOptionPane.showMessageDialog(null,"");}
                         

    }//GEN-LAST:event_t3ItemStateChanged

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
                                
       
    }//GEN-LAST:event_t4ActionPerformed

    private void t4InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_t4InputMethodTextChanged
 
    }//GEN-LAST:event_t4InputMethodTextChanged

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        t8.setText("");
        t1.setText(""); 
        t4.setText("");
        t5.setText(""); 
        t7.setText("");
         try
        {
         
        Class.forName("com.mysql.jdbc.Driver");
        Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
        Statement ps=co.createStatement();
         
        ResultSet rs=ps.executeQuery(" select * from  stockentry ORDER BY stock_id DESC LIMIT 1;"); 
        
        while(rs.next())
        {
          //  model.addRow(new Ob  
            
             int a=rs.getInt(7);
             if(a==0)
             {
                 t8.setText("1");
             }
             int c=a+1;
             t8.setText(""+c);
        } 
   
        }catch(Exception e){JOptionPane.showMessageDialog(null,e);}
        
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
                UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
                //</editor-fold>
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stockentery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel j13;
    private javax.swing.JLabel j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton price;
    private javax.swing.JButton save;
    private javax.swing.JTextField t1;
    private javax.swing.JComboBox<String> t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private com.toedter.calendar.JDateChooser t6;
    private javax.swing.JLabel t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables
}
